Refactor/powerbi
sfbrigade/data-covid19-sfbayarea pull request #151
Opened 2020-11-05 03:37 UTC by rickpr

2020-11-05 06:20 UTC, rickpr commented
Not sure what exactly to do about the `mypy` errors . Looking into it.

2020-11-05 07:34 UTC, Mr0grog commented
Ah, I’ll bet you’re getting errors like:

```
covid19_sfbayarea/data/san_mateo/power_bi_querier.py:1: error: Cannot find implementation or library stub for module named 'covid19_sfbayarea.data.power_bi.querier'
```

Because you aren’t using relative imports, and we don’t actually install the module in CI (because we don’t have a real `setup.py`):

https://github.com/sfbrigade/data-covid19-sfbayarea/blob/7b1876f0caa851e6a6e53f02cb31a2e5d174d0d6/.circleci/config.yml#L12-L22

2020-11-19 04:26 UTC, rickpr commented
Restricted this to sharing just the most useful parts an figured out the mypy errors. Might follow up with more stuff, but I think this is good for one PR.

2020-11-19 04:26 UTC, rickpr commented
So it turned out the folder I was importing from needed a `__init__.py` - that solved the `Cannot find implementation or library stub for module`

2020-11-19 07:03 UTC, Mr0grog requested changes

2020-11-19 07:03 UTC, Mr0grog commented on covid19_sfbayarea/data/power_bi/querier.py
> +        response = post(self.base_uri, headers = { 'X-PowerBI-ResourceKey': self.powerbi_resource_key }, json = self._query_params())
Would be nice to reformat this across multiple lines for readability.

2020-11-19 07:07 UTC, Mr0grog commented on covid19_sfbayarea/data/power_bi/querier.py
> +        return [ bool(int(one_or_zero)) for one_or_zero in r_in_binary ]
Fixed a typo in comment above, if following by e-mail.

2020-11-19 20:40 UTC, rickpr commented on covid19_sfbayarea/data/power_bi/querier.py
> +        return [ bool(int(one_or_zero)) for one_or_zero in r_in_binary ]
Thanks for the great explanation and cool simplification of this!

2023-01-21 16:49 UTC, closed without merging